import { ButtonComponent } from "button_component.slint";
import { LineEditComponent } from "line_edit_component.slint";
import { TextComponent } from "text_component.slint";

export component AppWindow inherits Window {
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            TextComponent {}
        }
        Row {
            LineEditComponent {}
        }
        Row {
            ButtonComponent {}
        }
    }
}
